# Generated by Django 4.2.9 on 2025-12-27 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONTACTED", "Contacted"),
                            ("QUALIFIED", "Qualified"),
                            ("CONVERTED", "Converted"),
                            ("LOST", "Lost"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_sid",
                    models.CharField(
                        db_index=True,
                        help_text="Twilio Call SID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "parent_call_sid",
                    models.CharField(
                        blank=True,
                        help_text="Parent Call SID for transferred calls",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("INBOUND", "Incoming"), ("OUTBOUND", "Outgoing")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("RINGING", "Ringing"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("BUSY", "Busy"),
                            ("FAILED", "Failed"),
                            ("NO_ANSWER", "No Answer"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                (
                    "from_number",
                    models.CharField(help_text="Caller's phone number", max_length=20),
                ),
                (
                    "to_number",
                    models.CharField(
                        help_text="Receiver's phone number", max_length=20
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=0, help_text="Call duration in seconds"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, help_text="Call start time", null=True
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, help_text="Call end time", null=True
                    ),
                ),
                (
                    "call_notes",
                    models.TextField(
                        blank=True, help_text="Notes about the call", null=True
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sales agent handling the call",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated contact",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="calls.contact",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated lead",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="calls.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call",
                "verbose_name_plural": "Calls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CallRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recording_sid",
                    models.CharField(
                        db_index=True,
                        help_text="Twilio Recording SID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "recording_url",
                    models.URLField(help_text="Twilio recording URL", max_length=500),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=0, help_text="Recording duration in seconds"
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, help_text="File size in bytes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("DELETED", "Deleted"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                (
                    "local_file",
                    models.FileField(
                        blank=True,
                        help_text="Local copy of the recording",
                        null=True,
                        upload_to="recordings/",
                    ),
                ),
                (
                    "is_transcribed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the recording has been transcribed",
                    ),
                ),
                (
                    "transcription",
                    models.TextField(
                        blank=True, help_text="Call transcription", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call",
                    models.ForeignKey(
                        help_text="Associated call",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="calls.call",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Recording",
                "verbose_name_plural": "Call Recordings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recording_sid"], name="calls_callr_recordi_cc984e_idx"
                    ),
                    models.Index(
                        fields=["call", "-created_at"],
                        name="calls_callr_call_id_56ba24_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["call_sid"], name="calls_call_call_si_7a505b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["agent", "-created_at"], name="calls_call_agent_i_387037_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["status", "-created_at"], name="calls_call_status_9a55d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["direction", "-created_at"],
                name="calls_call_directi_a0545e_idx",
            ),
        ),
    ]
